# -*- coding: utf-8 -*-
"""MATPLOT LIB

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ouBNZJbszX8VcJW9S_Dh4lT-EBrskCQe
"""

import matplotlib.pyplot as plt
import numpy as np
#It takes x points as [0,1,2,3]
y=np.array([2,3,8,10])
plt.plot(y,'D-g')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
#It takes x points as [0,1,2,3]
y=np.array([2,3,8,10])
plt.plot(y,'D--r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
#It takes x points as [0,1,2,3]
y=np.array([2,3,8,10])
plt.plot(y,'o--c')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
#It takes x points as [23,4,5,3]
y=np.array([2,3,8,10])
plt.plot(y,'o--y')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([2,3,4,56])
plt.plot(y,'o-.g')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([2,3,8,10])
plt.plot(y,'o-.g',ms=10,mec='b',mfc='r')
plt.show()

#mec-- marker edge color
#ms-- marker size
#mfc-- marker fill color

import matplotlib.pyplot as plt
import numpy as np
y=np.array([2,3,8,10])
plt.plot(y,'o-.g',ms=10000,mec='#ff00ff',mfc='#ffff00')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([2,3,8,10])
plt.plot(y,linestyle='dashed')
plt.show()
print()

import matplotlib.pyplot as plt
import numpy as np
y1=np.array([2,3,8,10])
y2=np.array([1,4,9,12])
plt.plot(y1,linestyle='-',c='b')
plt.plot(y2,linestyle='-',c='r')
plt.show()
print()

import matplotlib.pyplot as plt
import numpy as np
x1=np.array([1,2,3,4,5])
x2=np.array([1,2,3,4,5])
y1=np.array([14,18,8,10,9])
y2=np.array([10,8,12,12,15])
plt.plot(x1,y1,x2,y2)
plt.xlabel('overs')
plt.ylabel('runs')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x1=np.array([1,2,3,4,5])
y1=np.array([12,13,14,15,16])
plt.subplot(1,2,1)
plt.plot(x1,y1)
font1={'family':'serif','color':'blue','size':20}
font2={'family':'serif','color':'darkred','size':15}
plt.title('India',fontdict=font1)
plt.xlabel('overs',fontdict=font1)
plt.ylabel('runs',fontdict=font2)
x2=np.array([1,2,3,4,5])
y2=np.array([10,8,12,2,15])
plt.subplot(1,2,2)
plt.plot(x2,y2)
plt.title('Austrila',fontdict=font1)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([1, 2, 3, 4, 5])
y1 = np.array([14, 15, 17, 18, 20])
y2 = np.array([14, 15, 16, 17, 18])
y3 = np.array([12, 14, 16, 18, 20])
y4 = np.array([13, 15, 17, 19, 21])

plt.subplot(2, 2, 1)
plt.plot(x, y1)

plt.subplot(2, 2, 2)
plt.plot(x, y2)

plt.subplot(2, 2, 3)
plt.plot(x, y3)

plt.subplot(2, 2, 4)
plt.plot(x, y4)

plt.show()